### PR TITLE
Display correct version no of sinix.js package

### LINKED ISSUE #12: Ouput version number whenever there `sinix` command executes
**Note:** This issue is reserved for SLoP Contributors.

The output should be in the following format.
```
$ npm run sinix build
sinix.js v0.1

// output from build command
```

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
Made required changes to display the version no of the package everytime 'sinix' command is run according to issue #12 .

### CODE REVIEW

**Review by janvig — CHANGES_REQUESTED** [review]
@Devansu-Yadav Pull your branch again as there are new changes. Then please revert all the changes done by you except the ones in bin/sinix.js, as they aren't required.

**Comment by Devansu-Yadav** [comment]
@janvig As in I revert the changes in the package.json, sinix.config.js, and also the package-lock.json, right?

**Comment by janvig** [comment]
Yes.

**Review by janvig — CHANGES_REQUESTED** [review]
Run `$ npm run lint:fix` to fix the linting errors in order to pass Travis CI checks and push.

**Review by janvig — APPROVED** [review]

**Comment by sanket143** [comment]
give @Devansu-Yadav 25 points

**Pull request merged**
