### PR TITLE
Enabled eslint on channel/index.js

### LINKED ISSUE #9: Enable eslint in channel/index.js

### PR DESCRIPTION
**Pull request by AnirudhPanda**
@janvig check it please!

### CODE REVIEW

**Comment by janvig** [comment]
Resolves #9
@AnirudhPanda Did you encounter any errors on running `$ npm run lint`?

**Comment by sanket143** [comment]
give @AnirudhPanda 5 points

**Comment by AnirudhPanda** [comment]
> @AnirudhPanda Did you encounter any errors on running `$ npm run lint`?

Yeah 4 errors about variables being declared but not used.

**Review by janvig — CHANGES_REQUESTED** [review]
Fix the linting errors and push the changes.

**Review by janvig — APPROVED** [review]
All good :+1:

**Comment by sanket143** [comment]
give @AnirudhPanda 25 points

**Pull request merged**
